---
variables:
  - &file Dockerfile
  - &dhub https://index.docker.io/v1/
  - &arch linux/arm/v7,linux/arm64/v8,linux/amd64,linux/i386
  - &repo bksolutions/holdingnuts


steps:      
#  publish:
#    when:
#      branch: main
#    image: woodpeckerci/plugin-docker-buildx
#    settings:
#      dockerfile: *file
#      platforms: *arch
#      dry_run: false
#      repo: *repo
#      tags: 
#        - 'latest'
#        - '0.0.5'
#      registry: *dhub
#      logins:
#        - registry: *dhub
#          username:
#            from_secret: DOCKER_BKSOL_USER
#          password:
#            from_secret: DOCKER_BKSOL_PASS

  test:
    image: alpine
    environment:
      APARAM1: 'Parameter 1'
      APARAM2:
        from_secret: DOCKER_BKSOL_USER
    commands:
      - echo $$APARAM1
      - echo $$APARAM2

#  update_doc:
#    when:
#      branch: main
#    image: peterevans/dockerhub-description:3
#    environment:
#      DOCKERHUB_USERNAME:
#        from_secret: DOCKER_BKSOL_USER
#      DOCKERHUB_PASSWORD: 
#        from_secret: DOCKER_BKSOL_PASS
#      DOCKERHUB_REPOSITORY: *repo
#      README_FILEPATH: ${CI_WORKSPACE}/README.md