---
steps:
  build-amd64
    image: woodpeckerci/plugin-docker-buildx
    pull: if-not-exists
    settings:
      dry_run: true
      repo: bksolutions/holdingnuts
      tags:
        - 'latest'
        - '0.0.5'
