---
variables:
  - &file Dockerfile
  - &dhub https://index.docker.io/v1/
  - &arch linux/arm/v7,linux/arm64/v8,linux/amd64,linux/i386
  - &repo bksolutions/holdingnuts

steps:
  build_n_push:
    when:
      - event: [push]
        branch: main
        path:
          include: ['Dockerfile', 'HoldingnutsServerCfg', '.woodpecker/dockerhub_deploy.yml']
      - event: [cron, manual]
        branch: main
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: *arch
      dry_run: false
      repo: *repo
      tags: 
        - 'latest'
        - '0.0.5'
      build_args:
        - VERSION="0.0.5"
        - CREATED="${CI_PIPELINE_STARTED}"
        - REVISION="${CI_COMMIT_SHA}"
      registry: *dhub
      logins:
        - registry: *dhub
          username:
            from_secret: DOCKER_BKSOL_USER
          password:
            from_secret: DOCKER_BKSOL_PASS
