---
steps:
  lint_doc:
    when:
      event: [push]
      path:
        include: ['*.TEST']
      #  include: ['*.md', '.woodpecker/prettier_md.yml', '.woodpecker/dockerhub_doc.yml']
    image: woodpeckerci/plugin-prettier:next --check